name: Auto Accept Collabs

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: 0 * * * *

jobs:
  auto_accept_collab:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master

      - name: Auto Accept Collabs
        uses: kbrashears5/github-action-auto-accept-collabs@master
        with:
          TOKEN: ${{ secrets.TOKEN }}
          
      - uses: cinotify/github-action@main
        with:
          to: 'duyet.cs@gmail.com'
          subject: '[duyetbot] accepted github collabs'
          body: '[duyetbot] accepted github collabs'
