name: crates pull
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  puller:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - run: |
          cargo init
          cargo add $CRATES
          cargo fetch
        env:
          CRATES: statsd-mock grant
